// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateUser struct {
	Name string `json:"name"`
}

// Diagnostic это документ диагностики который может быть привязан к талону ремонта
type Diagnostic struct {
	ID            int       `json:"id"`
	Version       int       `json:"version"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	DefinedNumber string    `json:"definedNumber"`
	Sku           string    `json:"sku"`
}

type UpdateDiagnostic struct {
	ID            int    `json:"id"`
	DefinedNumber string `json:"definedNumber"`
	Sku           string `json:"sku"`
}

// User is out user
type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
