// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Diagnostic struct {
	ID            int       `json:"id"`
	Version       int       `json:"version"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	DefinedNumber string    `json:"definedNumber"`
	Sku           string    `json:"sku"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
