services:

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: restar
      POSTGRES_PASSWORD: restar
      POSTGRES_DB: restar
      PG_DATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ../../.bin/db:/var/lib/postgresql/data
      - ../../configs/sql:/docker-entrypoint-initdb.d

  storage:
    image: chrislusf/seaweedfs:3.33
    command: 'server -webdav -s3 -dir /data'
    ports:
      - 8333:8333 # s3 api
      - 9333:9333 # cluster ui
      - 8080:8080 # node ui
      - 8888:8888 # filer ui
      - 7333:7333 # webdav ui

    volumes:
#      - ../../.bin/storage:/data
      - /media/fess932/ssd2/target:/data


  fulltext:
    image: getmeili/meilisearch:v0.29.1
    environment:
      - MEILI_DB_PATH=/data.ms
    ports:
      - 7700:7700
    volumes:
      - ../../.bin/fulltext:/data.ms