### test user request
GRPC {{host}}/UserService/UserInfo

{
  "id": "фывфыв23"
}

### create diagnostic request
GRPC {{host}}/DiagnosticService/Create

{
  "definedNumber" : "cs125",
  "sku": "123123",
  "images": []
}
