### DiagnosticList
GRAPHQL http://localhost:8090/query
Content-Type: application/json

query DiagnosticList {
    diagnosticList {
        id
        version
        createdAt
        updatedAt
        sku
        definedNumber
    }
}

### Create diagnostic
GRAPHQL http://localhost:8090/query
Content-Type: application/json

mutation CreateDiagnostic {
    createDiagnostic {
        id
        version
        createdAt
        updatedAt
        sku
        definedNumber
    }
}

### Upload file to diagnostic
POST http://localhost:8090/query
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="operations"

{
  "query": "mutation ($file: Upload!) { diagnosticUploadFile(file: $file) }",
  "variables": { "file": null }
}

--boundary
Content-Disposition: form-data; name="map"

{ "0": ["variables.file"] }

--boundary
Content-Disposition: form-data; name="0"; filename="cat.jpg"
Content-Type: image/jpeg

< cat.jpg