### DiagnosticList
GRAPHQL http://localhost:9091/query
Content-Type: application/json

query DiagnosticList {
    diagnosticList {
        id
        version
        createdAt
        updatedAt
        sku
        definedNumber
    }
}

### Create diagnostic
GRAPHQL http://localhost:9091/query
Content-Type: application/json

mutation CreateDiagnostic {
    createDiagnostic {
        id
        version
        createdAt
        updatedAt
        sku
        definedNumber
    }
}